# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.cache/wt [current_project]
set_property parent.project_path C:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
set_property ip_repo_paths c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/vivado-library [current_project]
set_property ip_output_repo c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib C:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/hdl/DataHub_wrapper.v
add_files C:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/DataHub.bd
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_mig_7series_0_0/DataHub_mig_7series_0_0/user_design/constraints/DataHub_mig_7series_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_mig_7series_0_0/DataHub_mig_7series_0_0/user_design/constraints/DataHub_mig_7series_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_clk_wiz_0_0/DataHub_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_clk_wiz_0_0/DataHub_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_clk_wiz_0_0/DataHub_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_axi_uartlite_0_0/DataHub_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_axi_uartlite_0_0/DataHub_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_axi_uartlite_0_0/DataHub_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_microblaze_0_0/DataHub_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_microblaze_0_0/DataHub_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_microblaze_0_0/DataHub_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_microblaze_0_axi_intc_0/DataHub_microblaze_0_axi_intc_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_microblaze_0_axi_intc_0/DataHub_microblaze_0_axi_intc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_microblaze_0_axi_intc_0/DataHub_microblaze_0_axi_intc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_mdm_1_0/DataHub_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_mdm_1_0/DataHub_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_rst_clk_wiz_0_100M_0/DataHub_rst_clk_wiz_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_rst_clk_wiz_0_100M_0/DataHub_rst_clk_wiz_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_rst_clk_wiz_0_100M_0/DataHub_rst_clk_wiz_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_PmodWIFI_0_0/src/PmodWIFI_pmod_bridge_0_0/PmodWIFI_pmod_bridge_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_PmodWIFI_0_0/src/PmodWIFI_pmod_bridge_0_0/src/pmod_concat_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_PmodWIFI_0_0/src/PmodWIFI_axi_quad_spi_0_0/PmodWIFI_axi_quad_spi_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_PmodWIFI_0_0/src/PmodWIFI_axi_quad_spi_0_0/PmodWIFI_axi_quad_spi_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_PmodWIFI_0_0/src/PmodWIFI_axi_quad_spi_0_0/PmodWIFI_axi_quad_spi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_PmodWIFI_0_0/src/PmodWIFI_axi_quad_spi_0_0/PmodWIFI_axi_quad_spi_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_PmodWIFI_0_0/src/PmodWIFI_axi_gpio_0_0/PmodWIFI_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_PmodWIFI_0_0/src/PmodWIFI_axi_gpio_0_0/PmodWIFI_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_PmodWIFI_0_0/src/PmodWIFI_axi_gpio_0_0/PmodWIFI_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_PmodWIFI_0_0/src/PmodWIFI_axi_gpio_1_0/PmodWIFI_axi_gpio_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_PmodWIFI_0_0/src/PmodWIFI_axi_gpio_1_0/PmodWIFI_axi_gpio_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_PmodWIFI_0_0/src/PmodWIFI_axi_gpio_1_0/PmodWIFI_axi_gpio_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_PmodWIFI_0_0/src/PmodWIFI_axi_timer_0_0/PmodWIFI_axi_timer_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_PmodWIFI_0_0/src/PmodWIFI_axi_timer_0_0/PmodWIFI_axi_timer_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_PmodWIFI_0_0/DataHub_PmodWIFI_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_PmodWIFI_0_0/src/PmodWIFI_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_PmodSD_0_0/src/PmodSD_axi_gpio_0_0/PmodSD_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_PmodSD_0_0/src/PmodSD_axi_gpio_0_0/PmodSD_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_PmodSD_0_0/src/PmodSD_axi_gpio_0_0/PmodSD_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_PmodSD_0_0/src/PmodSD_axi_quad_spi_0_0/PmodSD_axi_quad_spi_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_PmodSD_0_0/src/PmodSD_axi_quad_spi_0_0/PmodSD_axi_quad_spi_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_PmodSD_0_0/src/PmodSD_axi_quad_spi_0_0/PmodSD_axi_quad_spi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_PmodSD_0_0/src/PmodSD_axi_quad_spi_0_0/PmodSD_axi_quad_spi_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_PmodSD_0_0/src/PmodSD_pmod_bridge_0_0/PmodSD_pmod_bridge_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_PmodSD_0_0/src/PmodSD_pmod_bridge_0_0/src/pmod_concat_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_PmodSD_0_0/DataHub_PmodSD_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_PmodSD_0_0/src/PmodSD_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_axi_gpio_0_0/DataHub_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_axi_gpio_0_0/DataHub_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_axi_gpio_0_0/DataHub_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_axi_gpio_1_0/DataHub_axi_gpio_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_axi_gpio_1_0/DataHub_axi_gpio_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_axi_gpio_1_0/DataHub_axi_gpio_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_axi_smc_0/bd_0/ip/ip_12/bd_3c62_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_axi_smc_0/bd_0/ip/ip_21/bd_3c62_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_axi_smc_0/bd_0/ip/ip_24/bd_3c62_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_axi_smc_0/bd_0/ip/ip_25/bd_3c62_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_axi_smc_0/bd_0/ip/ip_26/bd_3c62_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_axi_smc_0/bd_0/ip/ip_27/bd_3c62_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_axi_smc_0/bd_0/ip/ip_28/bd_3c62_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_axi_smc_0/bd_0/ip/ip_29/bd_3c62_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_axi_smc_0/bd_0/ip/ip_22/bd_3c62_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_axi_smc_0/bd_0/ip/ip_23/bd_3c62_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_axi_smc_0/bd_0/ip/ip_13/bd_3c62_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_axi_smc_0/bd_0/ip/ip_14/bd_3c62_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_axi_smc_0/bd_0/ip/ip_15/bd_3c62_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_axi_smc_0/bd_0/ip/ip_16/bd_3c62_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_axi_smc_0/bd_0/ip/ip_17/bd_3c62_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_axi_smc_0/bd_0/ip/ip_4/bd_3c62_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_axi_smc_0/bd_0/ip/ip_5/bd_3c62_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_axi_smc_0/bd_0/ip/ip_6/bd_3c62_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_axi_smc_0/bd_0/ip/ip_7/bd_3c62_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_axi_smc_0/bd_0/ip/ip_8/bd_3c62_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_axi_smc_0/bd_0/ip/ip_1/bd_3c62_psr0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_axi_smc_0/bd_0/ip/ip_1/bd_3c62_psr0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_axi_smc_0/bd_0/ip/ip_2/bd_3c62_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_axi_smc_0/bd_0/ip/ip_2/bd_3c62_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_axi_smc_0/bd_0/ip/ip_3/bd_3c62_psr_aclk1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_axi_smc_0/bd_0/ip/ip_3/bd_3c62_psr_aclk1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_rst_mig_7series_0_81M_0/DataHub_rst_mig_7series_0_81M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_rst_mig_7series_0_81M_0/DataHub_rst_mig_7series_0_81M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_rst_mig_7series_0_81M_0/DataHub_rst_mig_7series_0_81M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_xbar_0/DataHub_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_dlmb_v10_0/DataHub_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_dlmb_v10_0/DataHub_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_ilmb_v10_0/DataHub_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_ilmb_v10_0/DataHub_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_dlmb_bram_if_cntlr_0/DataHub_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_ilmb_bram_if_cntlr_0/DataHub_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/ip/DataHub_lmb_bram_0/DataHub_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/Keith/Documents/Git/568_Hub/568_WiFi/DataHub-Vivado/DataHub-Vivado.srcs/sources_1/bd/DataHub/DataHub_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top DataHub_wrapper -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef DataHub_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file DataHub_wrapper_utilization_synth.rpt -pb DataHub_wrapper_utilization_synth.pb"
