# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/DataHub/DataHub.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DataHub || ORIG_REF_NAME==DataHub} -quiet] -quiet

# IP: bd/DataHub/ip/DataHub_mig_7series_0_0/DataHub_mig_7series_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DataHub_mig_7series_0_0 || ORIG_REF_NAME==DataHub_mig_7series_0_0} -quiet] -quiet

# IP: bd/DataHub/ip/DataHub_clk_wiz_0_0/DataHub_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DataHub_clk_wiz_0_0 || ORIG_REF_NAME==DataHub_clk_wiz_0_0} -quiet] -quiet

# IP: bd/DataHub/ip/DataHub_axi_uartlite_0_0/DataHub_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DataHub_axi_uartlite_0_0 || ORIG_REF_NAME==DataHub_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/DataHub/ip/DataHub_microblaze_0_0/DataHub_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DataHub_microblaze_0_0 || ORIG_REF_NAME==DataHub_microblaze_0_0} -quiet] -quiet

# IP: bd/DataHub/ip/DataHub_microblaze_0_axi_periph_0/DataHub_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DataHub_microblaze_0_axi_periph_0 || ORIG_REF_NAME==DataHub_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/DataHub/ip/DataHub_microblaze_0_axi_intc_0/DataHub_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DataHub_microblaze_0_axi_intc_0 || ORIG_REF_NAME==DataHub_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/DataHub/ip/DataHub_microblaze_0_xlconcat_0/DataHub_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DataHub_microblaze_0_xlconcat_0 || ORIG_REF_NAME==DataHub_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/DataHub/ip/DataHub_mdm_1_0/DataHub_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DataHub_mdm_1_0 || ORIG_REF_NAME==DataHub_mdm_1_0} -quiet] -quiet

# IP: bd/DataHub/ip/DataHub_rst_clk_wiz_0_100M_0/DataHub_rst_clk_wiz_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DataHub_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==DataHub_rst_clk_wiz_0_100M_0} -quiet] -quiet

# IP: bd/DataHub/ip/DataHub_PmodWIFI_0_0/DataHub_PmodWIFI_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DataHub_PmodWIFI_0_0 || ORIG_REF_NAME==DataHub_PmodWIFI_0_0} -quiet] -quiet

# IP: bd/DataHub/ip/DataHub_PmodSD_0_0/DataHub_PmodSD_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DataHub_PmodSD_0_0 || ORIG_REF_NAME==DataHub_PmodSD_0_0} -quiet] -quiet

# IP: bd/DataHub/ip/DataHub_axi_gpio_0_0/DataHub_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DataHub_axi_gpio_0_0 || ORIG_REF_NAME==DataHub_axi_gpio_0_0} -quiet] -quiet

# IP: bd/DataHub/ip/DataHub_axi_gpio_1_0/DataHub_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DataHub_axi_gpio_1_0 || ORIG_REF_NAME==DataHub_axi_gpio_1_0} -quiet] -quiet

# IP: bd/DataHub/ip/DataHub_axi_smc_0/DataHub_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DataHub_axi_smc_0 || ORIG_REF_NAME==DataHub_axi_smc_0} -quiet] -quiet

# IP: bd/DataHub/ip/DataHub_rst_mig_7series_0_81M_0/DataHub_rst_mig_7series_0_81M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DataHub_rst_mig_7series_0_81M_0 || ORIG_REF_NAME==DataHub_rst_mig_7series_0_81M_0} -quiet] -quiet

# IP: bd/DataHub/ip/DataHub_xbar_0/DataHub_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DataHub_xbar_0 || ORIG_REF_NAME==DataHub_xbar_0} -quiet] -quiet

# IP: bd/DataHub/ip/DataHub_dlmb_v10_0/DataHub_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DataHub_dlmb_v10_0 || ORIG_REF_NAME==DataHub_dlmb_v10_0} -quiet] -quiet

# IP: bd/DataHub/ip/DataHub_ilmb_v10_0/DataHub_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DataHub_ilmb_v10_0 || ORIG_REF_NAME==DataHub_ilmb_v10_0} -quiet] -quiet

# IP: bd/DataHub/ip/DataHub_dlmb_bram_if_cntlr_0/DataHub_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DataHub_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==DataHub_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/DataHub/ip/DataHub_ilmb_bram_if_cntlr_0/DataHub_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DataHub_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==DataHub_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/DataHub/ip/DataHub_lmb_bram_0/DataHub_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DataHub_lmb_bram_0 || ORIG_REF_NAME==DataHub_lmb_bram_0} -quiet] -quiet

# XDC: bd/DataHub/DataHub_ooc.xdc
